### ISSUE TITLE
Consider using the same input and output payloads like OpenAI or / and Mistral

### ISSUE THREAD

**Issue by michaelwechner** [Repositorium-ch/embedding-service#4]
OpenAI: https://platform.openai.com/docs/guides/embeddings/how-to-get-embeddings

Mistral: https://docs.mistral.ai/api/#operation/createEmbedding

**Comment by colin-r-carter** [comment]
@michaelwechner should now be using the same standard with 42eeba01b3489205e932e11ccbde32894b152ff3
